package main

import (
	"fmt"
)

// import "time"

// import "pk1"

func main() {
	fmt.Println("hello world 5")

	// loop1()
	// days()
	// whatday(1)
	// whatday(2)
	// whatday(3)
	// whatday(4)
	// whatday(5)
	// whatday(6)
	// whatday(7)
	// whatday(8)
	// arr2()
	// matrix()
	// imatrix(4)
	// slice1()
	// slice2()
	// slice3()
	// pointer1()
	// variadic()
	// resursion(3)
	// resursionpattern(3)
	// sortdemo()
	// structdemo()

	// advslice()
	// readfiledemo()
	// read2()
	// channel()
	// channel1_2()
	// go goroutine(0)
	// time.Sleep(time.Second * 1)
	// ftest()
	// writefiledemo()
	// mapdemo()
	// mapdemo2()
	// methoddemo()
	// interfacedemo()
	// interfacedemo2()
	// goroutine2()
	// channeldemo()
	// channeltest()
	// channelparm()
	// regexdemo2()
	// template_demo()
	// template_demo2()
	// template_demo3()
	// httpGet()
	// httpPost()
	// httpClient()
	// httpPostForm()
	// httppost()
	// httppost2()
	// bater.Httpcookie()
	// bater.Gindemo()
	// httphtml()
	// httpfileserver()
	// httpmain()

	// httpallsp()
	// collydemo()
	// collydemo2()
	// redisdemo()
	// redisgame()
	// httpcount()
	// apidemo()
	// apidemoint()
	// httpquerydemo()
	// martinidemo()
	// martinidemo2()
	// selectdemo()

	// stringsdemo()
	// timedemo()
	// logdemo()
	// jsondemo()

	// httpListenAndServe()
	// httpHandleJson()
	// muxdemo()
	// httpsitemap()
	// mysqldemo()
	// goroutinelockdemo()
	// defertest()
	// defertest2()
	// defertest3main()
	// errordemo()
	// errordemo2()
	// errordemo3()
	// bater.Channeldemo()
	// md5demo()
	// i := 11
	// fmt.Printf("Is %d even? %v\n", i, bater.Even(i))

	// leetcode
	// fmt.Println("twoSum", twoSum([]int{2, 7, 11, 15}, 9))
	// fmt.Println("twoSum2", twoSum2([]int{2, 7, 11, 15}, 9))
	// addTwoNumbers_main()
	// lengthOfLongestSubstring_demo()
	strconvdemo2()
}
